/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.view;

import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import dao.MucDonHangDAO;
import pojo.SQLServerDataProvider;
class NonEditableTableModel extends DefaultTableModel {
    public NonEditableTableModel(String[] columnNames) {
        super(columnNames, 0);
    }

    @Override
    public boolean isCellEditable(int row, int column) {
        return false; // Tất cả các ô đều không thể chỉnh sửa
    }
}
/**
 *
 * @author Admin
 */
public class MucDonHang extends javax.swing.JPanel {
private SQLServerDataProvider dataProvider;
                 
    DefaultTableModel dtm = new DefaultTableModel();
    Connection connection =null;
    Statement statement = null;
    ResultSet resultSet = null;
    /**
     * Creates new form jpnMucDonHang
     */
    public MucDonHang() {
        initComponents();
        String []tieuDe= {"Mã mục đơn hàng","Tên sản phẩm","Số lượng" ,"Giá", "Giảm giá hiện tại", "Tên đơn hàng"};
       dtm = new NonEditableTableModel(tieuDe); dtm = new NonEditableTableModel(tieuDe);
        dgvMDH.setModel(dtm);
        dataProvider  = new SQLServerDataProvider();
        dataProvider.open(); 
        connection = dataProvider.getConnection(); 
        loadBang();
        
        dgvMDH.addMouseListener(new java.awt.event.MouseAdapter() {
        public void dgvMDHMouseClicked(java.awt.event.MouseEvent evt) {
            dgvMDHMouseClicked(evt);
        }
    });
        
    }
    private void loadBang() {
    try {
        if (connection != null) {
            statement = connection.createStatement();
            String sqlSelect = "SELECT MDH.MAMUC, SP.TENSP, MDH.SOLUONG, MDH.GIAHIENTAI, MDH.GIAMGIAHIENTAI, DH.TENDONHANG " +
                               "FROM MUCDONHANG MDH " +
                               "JOIN SanPham SP ON MDH.MASP = SP.MASP " +
                               "JOIN DONHANG DH ON MDH.MADONHANG = DH.MADONHANG";
            resultSet = statement.executeQuery(sqlSelect);

            dtm.setRowCount(0); // Xóa các dòng cũ trước khi tải dữ liệu mới

            while (resultSet.next()) {
                int maMuc = resultSet.getInt(1);
                String tenSP = resultSet.getString(2);
                int soLuong = resultSet.getInt(3);
                double giaHienTai = resultSet.getDouble(4);
                double giamGiaHienTai = resultSet.getDouble(5);
                String tenDonHang = resultSet.getString(6);

                Object[] rowData = {maMuc, tenSP, soLuong, giaHienTai, giamGiaHienTai, tenDonHang};
                dtm.addRow(rowData);
            }
        } else {
            System.out.println("Không thể kết nối tới CSDL.");
        }
    } catch (SQLException ex) {
        Logger.getLogger(MucDonHang.class.getName()).log(Level.SEVERE, null, ex);
    } finally {
        try {
            if (resultSet != null) resultSet.close();
            if (statement != null) statement.close();
            if (connection != null) connection.close();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        dgvMDH = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lbTongGia = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbTen = new javax.swing.JLabel();
        lbTENDH = new javax.swing.JLabel();
        btnXoa = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 51));
        jPanel1.setPreferredSize(new java.awt.Dimension(1545, 930));

        jPanel3.setBackground(new java.awt.Color(204, 255, 204));
        jPanel3.setPreferredSize(new java.awt.Dimension(1545, 930));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("MỤC ĐƠN HÀNG");

        dgvMDH.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        dgvMDH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dgvMDHMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(dgvMDH);

        jLabel3.setText("Tên đơn hàng");

        jLabel5.setBackground(new java.awt.Color(255, 255, 0));
        jLabel5.setText("Tổng giá");

        lbTongGia.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbTongGia.setForeground(new java.awt.Color(255, 51, 51));

        jLabel4.setText("Tên sản phẩm");

        lbTen.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbTen.setForeground(new java.awt.Color(51, 51, 255));

        lbTENDH.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbTENDH.setForeground(new java.awt.Color(0, 0, 255));

        btnXoa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnXoa.setForeground(new java.awt.Color(255, 0, 0));
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lbTen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(202, 202, 202))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lbTENDH, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(lbTongGia, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(29, Short.MAX_VALUE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbTen, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbTENDH, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbTongGia, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 29, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 932, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(0, 601, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(455, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, 1533, 1533, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, 918, 918, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void dgvMDHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dgvMDHMouseClicked
        int selectedRow = dgvMDH.getSelectedRow();
        if (selectedRow != -1) { // Kiểm tra xem một hàng đã được chọn chưa
            String tenSanPham = (String) dgvMDH.getValueAt(selectedRow, 1);
            String tenDonHang = (String) dgvMDH.getValueAt(selectedRow, 5);
            double giaHienTai = (double) dgvMDH.getValueAt(selectedRow, 3);
            double giamGiaHienTai = (double) dgvMDH.getValueAt(selectedRow, 4);
            double tongGia = giaHienTai - giamGiaHienTai;

            // Cập nhật giá trị của các label
            lbTen.setText(" " + tenSanPham);
            lbTENDH.setText(" " + tenDonHang);
            lbTongGia.setText(" " + tongGia);

        }
    }//GEN-LAST:event_dgvMDHMouseClicked

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
    int[] selectedRows = dgvMDH.getSelectedRows();
if (selectedRows.length > 0) {
    int confirm = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn xóa các mục đã chọn?", "Xác nhận xóa", JOptionPane.YES_NO_OPTION);
    if (confirm == JOptionPane.YES_OPTION) {
        for (int i = selectedRows.length - 1; i >= 0; i--) {
            int selectedRow = selectedRows[i];
            long maMuc = (int) dgvMDH.getValueAt(selectedRow, 0); // Cột đầu tiên chứa maMuc
            try {
    // Thực hiện xóa mục đơn hàng
    boolean xoaThanhCong = MucDonHangDAO.xoaMucDonHang(maMuc);

        if (!xoaThanhCong) {
            // Nếu xóa không thành công, ném ra ngoại lệ SQLException với thông báo lỗi cụ thể
            throw new SQLException("Không thể xóa mục đơn hàng. Vui lòng kiểm tra lại kết nối cơ sở dữ liệu hoặc ràng buộc dữ liệu.");
        }

        // Nếu xóa thành công, tiếp tục thực hiện các thao tác khác
        dtm.removeRow(selectedRow);
        JOptionPane.showMessageDialog(this, "Xóa thành công.", "Thông báo", JOptionPane.INFORMATION_MESSAGE);

    } catch (SQLException ex) {
        // Xử lý ngoại lệ SQLException nếu có
        Logger.getLogger(MucDonHang.class.getName()).log(Level.SEVERE, null, ex);
        JOptionPane.showMessageDialog(this, "Lỗi khi xóa mục đơn hàng: " + ex.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
    }
            }
    }
} else {
    JOptionPane.showMessageDialog(this, "Vui lòng chọn ít nhất một hàng để xóa.", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
}
    }//GEN-LAST:event_btnXoaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnXoa;
    private javax.swing.JTable dgvMDH;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbTENDH;
    private javax.swing.JLabel lbTen;
    private javax.swing.JLabel lbTongGia;
    // End of variables declaration//GEN-END:variables
}
