/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.view;

import dao.NguoiDungDAO;
import pojo.NguoiDung;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class User extends javax.swing.JPanel {
    LocalDateTime currentDate = LocalDateTime.now();
    ArrayList<String> maNDList;
    NguoiDungDAO nguoidungdao;
    String action = "";
    public User() {
        initComponents();
        loadUser();
        jpnThongTin.setEnabled(false);

    }

    public void loadUser() {
        nguoidungdao = new NguoiDungDAO();
        maNDList = new ArrayList<>();

        DefaultTableModel model = new DefaultTableModel(new Object[]{
            "Mã Người Dùng", "Họ", "Tên", "Tên Tài Khoản", "Mật khẩu",
            "Chức Vụ", "Ngày Tạo", "Ngày Cập Nhật"}, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        ArrayList<NguoiDung> DSND = nguoidungdao.layDanhSachNguoiDung();

        if (DSND != null) {
            for (NguoiDung nd : DSND) {
                String maND = String.valueOf(nd.getMaND());
                maNDList.add(maND);
                DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
                model.addRow(new Object[]{
                    nd.getMaND(), nd.getHo(), nd.getTen(), nd.getTenTaiKhoan(),
                    nd.getMatKhau(), nd.getChucVu(), nd.getNgayTao().format(formatter), nd.getNgayCapNhat().format(formatter)
                });
            }
        } else {
            System.out.println("Error: DSND is null");
        }

        // Set the table model to the JTable
        jtbUser.setModel(model);
        jtbUser.getTableHeader().setReorderingAllowed(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbUser = new javax.swing.JTable();
        jpnThongTin = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtfMaND = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtfHo = new javax.swing.JTextField();
        jtfTen = new javax.swing.JTextField();
        jtfTenTaiKhoan = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jtfMatKhau = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jcbChucVu = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jbtThem = new javax.swing.JButton();
        jbtXoa = new javax.swing.JButton();
        jbtSua = new javax.swing.JButton();
        jbtLuu = new javax.swing.JButton();
        Reload = new javax.swing.JButton();
        jbtCapNhat = new javax.swing.JButton();

        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 238));
        jPanel1.setPreferredSize(new java.awt.Dimension(1545, 930));

        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jtbUser.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jtbUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtbUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbUserMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtbUser);

        jpnThongTin.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jpnThongTin.setEnabled(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Mã Người Dùng:");

        jtfMaND.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jtfMaND.setEnabled(false);
        jtfMaND.setRequestFocusEnabled(false);
        jtfMaND.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfMaNDActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Họ:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Tên:");

        jLabel4.setBackground(new java.awt.Color(204, 204, 204));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Tên Tài Khoản:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Chức Vụ:");

        jtfHo.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jtfHo.setEnabled(false);
        jtfHo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfHoActionPerformed(evt);
            }
        });

        jtfTen.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jtfTen.setEnabled(false);

        jtfTenTaiKhoan.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jtfTenTaiKhoan.setEnabled(false);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Mật Khẩu:");

        jtfMatKhau.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jtfMatKhau.setEnabled(false);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setText("QUẢN LÝ USER");

        jcbChucVu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Khách hàng" }));

        javax.swing.GroupLayout jpnThongTinLayout = new javax.swing.GroupLayout(jpnThongTin);
        jpnThongTin.setLayout(jpnThongTinLayout);
        jpnThongTinLayout.setHorizontalGroup(
            jpnThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnThongTinLayout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(jpnThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(10, 10, 10)
                .addGroup(jpnThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnThongTinLayout.createSequentialGroup()
                        .addGroup(jpnThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfMaND, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfHo, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jpnThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpnThongTinLayout.createSequentialGroup()
                                .addGap(112, 112, 112)
                                .addComponent(jLabel6))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnThongTinLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))))
                    .addComponent(jtfTen, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfTenTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnThongTinLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(12, 12, 12)))
                .addGroup(jpnThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtfMatKhau)
                    .addComponent(jcbChucVu, 0, 282, Short.MAX_VALUE))
                .addGap(310, 310, 310))
        );
        jpnThongTinLayout.setVerticalGroup(
            jpnThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnThongTinLayout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpnThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnThongTinLayout.createSequentialGroup()
                        .addGroup(jpnThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jtfMaND, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(jpnThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jtfHo, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(jtfMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(jpnThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jtfTen, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jpnThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jtfTenTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jpnThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jcbChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)))
                .addGap(81, 81, 81))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("CHỨC NĂNG"), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 102, 0))); // NOI18N

        jbtThem.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbtThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/Image/note_add.png"))); // NOI18N
        jbtThem.setText("Thêm");
        jbtThem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtThemMouseClicked(evt);
            }
        });
        jbtThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtThemActionPerformed(evt);
            }
        });

        jbtXoa.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbtXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/Image/delete.png"))); // NOI18N
        jbtXoa.setText("Xóa");
        jbtXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtXoaActionPerformed(evt);
            }
        });

        jbtSua.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbtSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/Image/fix.png"))); // NOI18N
        jbtSua.setText("Sửa");
        jbtSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtSuaActionPerformed(evt);
            }
        });

        jbtLuu.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbtLuu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/Image/save.png"))); // NOI18N
        jbtLuu.setText("Lưu");
        jbtLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtLuuActionPerformed(evt);
            }
        });

        Reload.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Reload.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/Image/refresh.png"))); // NOI18N
        Reload.setText("Reload");
        Reload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReloadActionPerformed(evt);
            }
        });

        jbtCapNhat.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbtCapNhat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/Image/update.png"))); // NOI18N
        jbtCapNhat.setText("Cập Nhật");
        jbtCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtCapNhatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jbtThem, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbtXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbtSua, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbtCapNhat)
                .addGap(18, 18, 18)
                .addComponent(Reload)
                .addGap(18, 18, 18)
                .addComponent(jbtLuu)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtThem, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbtXoa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtSua, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtCapNhat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Reload, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtLuu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpnThongTin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jpnThongTin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 50, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1325, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 876, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jtfMaNDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfMaNDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfMaNDActionPerformed

    private void jbtXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtXoaActionPerformed
        // TODO add your handling code here:
        int choice = JOptionPane.showConfirmDialog(jbtXoa, "Bạn có muốn xoá?", "Xác nhận xóa", JOptionPane.YES_NO_CANCEL_OPTION);
                if (choice == JOptionPane.YES_OPTION) {
        int row = jtbUser.getSelectedRow();
        if (row != -1) {
            long mand = Long.parseLong(maNDList.get(row));
            boolean kq = nguoidungdao.xoaNguoiDung(mand);
            if (kq == true) {
                JOptionPane.showMessageDialog(this, "Xoa thanh cong");
                loadUser();
            } else {
                JOptionPane.showMessageDialog(this, "Xoa that bai");
            }
            
        } else {
            JOptionPane.showMessageDialog(this, "Vui Long chon 1 dong");
        }
        
          } else if (choice == JOptionPane.NO_OPTION) {
                } else if (choice == JOptionPane.CANCEL_OPTION) {
                }
    }//GEN-LAST:event_jbtXoaActionPerformed

    private void jbtSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtSuaActionPerformed
        // TODO add your handling code here:
        int row = jtbUser.getSelectedRow();
        if (row != -1) {
            jtfHo.requestFocus();
            jtfMaND.setText(maNDList.get(row));
            jtfHo.setText((String) jtbUser.getValueAt(row, 1));
            jtfTen.setText((String) jtbUser.getValueAt(row, 2));
            jtfTenTaiKhoan.setText((String) jtbUser.getValueAt(row, 3));
            jtfMatKhau.setText((String) jtbUser.getValueAt(row, 4));
            jcbChucVu.setSelectedItem((String) jtbUser.getValueAt(row, 5));

        } 
    }//GEN-LAST:event_jbtSuaActionPerformed

    private void jtbUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbUserMouseClicked
        // TODO add your handling code here:
        int row = jtbUser.getSelectedRow();
        if (row != -1) {
        
            jtfMaND.setText(maNDList.get(row));
            jtfHo.setText((String) jtbUser.getValueAt(row, 1));
            jtfTen.setText((String) jtbUser.getValueAt(row, 2));
            jtfTenTaiKhoan.setText((String) jtbUser.getValueAt(row, 3));
            jtfMatKhau.setText((String) jtbUser.getValueAt(row, 4));
            jcbChucVu.setSelectedItem((String) jtbUser.getValueAt(row, 5));

        }
    }//GEN-LAST:event_jtbUserMouseClicked

    private void jbtThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtThemActionPerformed
        // TODO add your handling code here:
     
        
    }//GEN-LAST:event_jbtThemActionPerformed

    private void jtfHoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfHoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfHoActionPerformed

    private void jbtLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtLuuActionPerformed
        // TODO add your handling code here:
                         int choice = JOptionPane.showConfirmDialog(jbtXoa, "Bạn có muốn thêm người dùng này?", "Xác nhận thêm", JOptionPane.YES_NO_CANCEL_OPTION);
                if (choice == JOptionPane.YES_OPTION) {

        String ho = jtfHo.getText();
        String ten = jtfTen.getText();
        String tenTK = jtfTenTaiKhoan.getText();
        String  chucVu =  (String) jcbChucVu.getSelectedItem();
        String matKhau = jtfMatKhau.getText();
        LocalDateTime currentDate = LocalDateTime.now();
        String date = currentDate.toString();
        NguoiDung nd = new NguoiDung(ho,ten,tenTK,matKhau,chucVu);
        boolean kq = nguoidungdao.themNguoiDung(nd);
        if (kq == true) {
                JOptionPane.showMessageDialog(this, "Them thanh cong");
                loadUser();
            } else {
                JOptionPane.showMessageDialog(this, "Them that bai");
            }

          } else if (choice == JOptionPane.NO_OPTION) {
                } else if (choice == JOptionPane.CANCEL_OPTION) {
                }
    }//GEN-LAST:event_jbtLuuActionPerformed

    private void ReloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReloadActionPerformed
        // TODO add your handling code here:
        loadUser();
    }//GEN-LAST:event_ReloadActionPerformed

    private void jbtCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtCapNhatActionPerformed
        // TODO add your handling code here:
                int choice = JOptionPane.showConfirmDialog(jbtXoa, "Bạn có muốn cập nhật người dùng này?", "Xác nhận cập nhật", JOptionPane.YES_NO_CANCEL_OPTION);
                if (choice == JOptionPane.YES_OPTION) {


        Long maND = Long.parseLong(jtfMaND.getText());
        String ho = jtfHo.getText();
        String ten = jtfTen.getText();
        String tenTK = jtfTenTaiKhoan.getText();
        String  chucVu =  (String) jcbChucVu.getSelectedItem();
        String matKhau = jtfMatKhau.getText();
        NguoiDung nd = new NguoiDung(maND,ho,ten,tenTK,matKhau,chucVu);
        boolean kq = nguoidungdao.capNhatNguoiDung(nd);
        if (kq == true) {
                JOptionPane.showMessageDialog(this, "Cap nhat thanh cong");
            } else {
                JOptionPane.showMessageDialog(this, "Cap nhat that bai");
            }
                  } else if (choice == JOptionPane.NO_OPTION) {
                } else if (choice == JOptionPane.CANCEL_OPTION) {
                }
                loadUser();
    }//GEN-LAST:event_jbtCapNhatActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseClicked

    private void jbtThemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtThemMouseClicked
        // TODO add your handling code here:
        jpnThongTin.setEnabled(true);
          jtfHo.setEnabled(true);
        jtfTen.setEnabled(true);
        jtfTenTaiKhoan.setEnabled(true);
        jtfMatKhau.setEnabled(true);
        jcbChucVu.setEnabled(true);
        jtfMaND.setText("");
        jtfHo.requestFocus();
        jtfHo.setText("");
        jtfTen.setText("");
        jtfTenTaiKhoan.setText("");
        jtfMatKhau.setText("");
        jcbChucVu.setSelectedItem("");
    }//GEN-LAST:event_jbtThemMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Reload;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtCapNhat;
    private javax.swing.JButton jbtLuu;
    private javax.swing.JButton jbtSua;
    private javax.swing.JButton jbtThem;
    private javax.swing.JButton jbtXoa;
    private javax.swing.JComboBox<String> jcbChucVu;
    private javax.swing.JPanel jpnThongTin;
    private javax.swing.JTable jtbUser;
    private javax.swing.JTextField jtfHo;
    private javax.swing.JTextField jtfMaND;
    private javax.swing.JTextField jtfMatKhau;
    private javax.swing.JTextField jtfTen;
    private javax.swing.JTextField jtfTenTaiKhoan;
    // End of variables declaration//GEN-END:variables
}
