CREATE TRIGGER trg_after_insert_nhapkho
ON [NHAPKHO]
AFTER INSERT
AS
BEGIN
  DECLARE @MASP BIGINT, @SOLUONGNHAP INT;
  
  SELECT @MASP = MASP, @SOLUONGNHAP = SOLUONGNHAP FROM INSERTED;
  
  IF EXISTS (SELECT 1 FROM [HANGTONKHO] WHERE MASP = @MASP)
  BEGIN
    UPDATE [HANGTONKHO]
    SET SOLUONGTRONGKHO = SOLUONGTRONGKHO + @SOLUONGNHAP,
        NGAYNHAPHANG = GETDATE()
    WHERE MASP = @MASP;
  END
  ELSE
  BEGIN
    INSERT INTO [HANGTONKHO] (MASP, SOLUONGTRONGKHO, NGAYNHAPHANG, TRANGTHAI)
    VALUES (@MASP, @SOLUONGNHAP, GETDATE(), 'Còn hàng');
  END
END;
GO

CREATE TRIGGER trg_after_insert_xuatkho
ON [XUATKHO]
AFTER INSERT
AS
BEGIN
  DECLARE @MASP BIGINT, @SOLUONGXUAT INT;
  
  SELECT @MASP = MASP, @SOLUONGXUAT = SOLUONGXUAT FROM INSERTED;
  
  IF EXISTS (SELECT 1 FROM [HANGTONKHO] WHERE MASP = @MASP)
  BEGIN
    UPDATE [HANGTONKHO]
    SET SOLUONGTRONGKHO = SOLUONGTRONGKHO - @SOLUONGXUAT,
        NGAYXUATHANG = GETDATE(),
        TRANGTHAI = CASE 
                      WHEN SOLUONGTRONGKHO - @SOLUONGXUAT <= 0 THEN 'Hết hàng'
                      ELSE 'Còn hàng'
                    END
    WHERE MASP = @MASP;
  END
END;
GO
