ALTER TABLE MUCDONHANG
    DROP CONSTRAINT FK_MUCDONHANG_DONHANG;
GO

ALTER TABLE MUCDONHANG
    ADD CONSTRAINT FK_MUCDONHANG_DONHANG
        FOREIGN KEY (MADONHANG)
            REFERENCES DONHANG (MADONHANG)
            ON DELETE CASCADE ON UPDATE NO ACTION;
GO

ALTER TABLE HOADON
    DROP CONSTRAINT FK_HOADON_DONHANG;
GO

ALTER TABLE HOADON
    ADD CONSTRAINT FK_HOADON_DONHANG
        FOREIGN KEY (MADONHANG)
            REFERENCES DONHANG (MADONHANG)
            ON DELETE CASCADE;
GO

ALTER TABLE HOADON
    DROP CONSTRAINT FK_HOADON_NGUOIDUNG;
GO
ALTER TABLE HOADON
    ADD CONSTRAINT FK_HOADON_NGUOIDUNG
        FOREIGN KEY (MAND)
            REFERENCES NGUOIDUNG (MAND)
            ON DELETE CASCADE;