CREATE TRIGGER trg_insert_update_hangtonkho_nhapkho
ON [HANGTONKHO]
AFTER INSERT, UPDATE
AS
BEGIN
    DECLARE @MASP BIGINT, @SOLUONGTRONGKHO INT, @SOLUONGCU INT, @NGAYNHAPHANG DATETIME2;
    
    SELECT @MASP = MASP, @SOLUONGTRONGKHO = SOLUONGTRONGKHO, @NGAYNHAPHANG = NGAYNHAPHANG 
    FROM INSERTED;
    
    SELECT @SOLUONGCU = SOLUONGTRONGKHO 
    FROM DELETED
    WHERE MASP = @MASP;
    
    IF @SOLUONGCU IS NULL OR @SOLUONGTRONGKHO > @SOLUONGCU
    BEGIN
        DECLARE @SOLUONGNHAP INT;
        SET @SOLUONGNHAP = @SOLUONGTRONGKHO - ISNULL(@SOLUONGCU, 0);
        
        UPDATE [HANGTONKHO]
        SET SOLUONGTRONGKHO = @SOLUONGTRONGKHO, NGAYNHAPHANG = GETDATE()
        WHERE MASP = @MASP;
        
        INSERT INTO [NHAPKHO] (MASP, SOLUONGNHAP, NGAYNHAP, MAND)
        VALUES (@MASP, @SOLUONGNHAP, @NGAYNHAPHANG, 1); -- Giả định MAND là 1
    END
END;
GO

CREATE TRIGGER trg_insert_update_hangtonkho_xuatkho
ON [HANGTONKHO]
AFTER INSERT, UPDATE
AS
BEGIN
    DECLARE @MASP BIGINT, @SOLUONGTRONGKHO INT, @SOLUONGCU INT, @NGAYXUATHANG DATETIME2;
    
    SELECT @MASP = MASP, @SOLUONGTRONGKHO = SOLUONGTRONGKHO 
    FROM INSERTED;
    
    SELECT @SOLUONGCU = SOLUONGTRONGKHO 
    FROM DELETED
    WHERE MASP = @MASP;
    
    IF @SOLUONGTRONGKHO < @SOLUONGCU
    BEGIN
        DECLARE @SOLUONGXUAT INT;
        SET @SOLUONGXUAT = @SOLUONGCU - @SOLUONGTRONGKHO;
        
        UPDATE [HANGTONKHO]
        SET SOLUONGTRONGKHO = @SOLUONGTRONGKHO, NGAYXUATHANG = GETDATE()
        WHERE MASP = @MASP;
        
        INSERT INTO [XUATKHO] (MASP, SOLUONGXUAT, NGAYXUAT, MAND)
        VALUES (@MASP, @SOLUONGXUAT, GETDATE(), 1); -- Giả định MAND là 1
    END
END;
GO
