/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package khachhang;

import dao.DanhMucDAO;
import dao.DonHangDAO;
import dao.MucDonHangDAO;
import dao.NguoiDungDAO;
import dao.SanPhamDAO;
import pojo.DanhMuc;
import pojo.DonHang;
import pojo.MucDonHang;
import pojo.NguoiDung;
import pojo.SQLServerDataProvider;
import pojo.SanPham;
import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class Menu extends javax.swing.JFrame {
    private SQLServerDataProvider dataProvider;
    private static long maND;
    private static String ho;
    private static String ten;
    int x = 210;    //chieu rong
    int y = 835;    //chieu cao

    /**
     * Creates new form Menu
     */
    public Menu(long maND,String ho, String ten) {
        initComponents();
        cardMuaHang.setVisible(true);
        cardThongTinKH.setVisible(false);
        jplSlideMenu.setSize(210, 600);
        Menu.maND = maND;
        Menu.ho = ho;
        Menu.ten = ten;
        lable_TenKhachHang.setText(ho + " " + ten);
        dataProvider = new SQLServerDataProvider();
        dataProvider.open(); // Mở kết nối tới cơ sở dữ liệu
        loadData();
    }
    private void loadData() {
        ArrayList<DanhMuc> danhMucList = DanhMucDAO.layDanhSachDanhMuc();
        DefaultListModel<String> listModel = new DefaultListModel<>();
        for (DanhMuc danhMuc : danhMucList) {
            listModel.addElement(danhMuc.getTenDanhMuc()); // Thêm tên của từng danh mục vào listModel
        }
        listDanhMuc.setModel(listModel); // Hiển thị danh sách danh mục trong listDanhMuc
        ArrayList<SanPham> dsSanPham = SanPhamDAO.layDanhSachSanPham();
        DefaultTableModel dtmSanPham = (DefaultTableModel)tblDanhSachMatHang.getModel();
        dtmSanPham.setRowCount(0);
        for(SanPham sp:dsSanPham)
        {
            Vector<Object> vec = new Vector<Object>();
            vec.add(sp.getMaSanPham());
            vec.add(sp.getTenSanPham());
            vec.add(sp.getGia());
            vec.add(sp.getGiamGia());
            vec.add(sp.getMoTa());
            dtmSanPham.addRow(vec);
        }
        tblDanhSachMatHang.setModel(dtmSanPham);
        ThongTinKhachHang();
        hienThiDanhSachDonHangCuaNguoiDung();
    }
    public void openMenu() {
        jplSlideMenu.setSize(x, y);
        if (x == 0) {
            new Thread(new Runnable() {
                @Override
                public void run() {
                    try {
                        for (int i = 0; i <= 210; i++) {
                            jplSlideMenu.setSize(i, y);
                            Thread.sleep(1);
                        }
                    } catch (Exception e) {
                    }
                }
            }).start();
            x = 210;
        }
    }

    public void closeMenu() {
        jplSlideMenu.setSize(x, y);
        if (x == 210) {
            new Thread(new Runnable() {
                @Override
                public void run() {
                    try {
                        for (int i = 210; i >= 0; i--) {
                            jplSlideMenu.setSize(i, y);
                            Thread.sleep(2);
                        }
                    } catch (Exception e) {
                    }
                }
            }).start();
            x = 0;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jplSlideMenu = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lable_TenKhachHang = new javax.swing.JLabel();
        lblCloseMenu = new javax.swing.JLabel();
        lblMuaHang = new javax.swing.JLabel();
        lblThongTinKH = new javax.swing.JLabel();
        lblLichSuMuaHang = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        labelDangXuat = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jpllMenuBar = new javax.swing.JPanel();
        lblOpenMenu = new javax.swing.JLabel();
        jplTitle = new javax.swing.JPanel();
        jplMain = new javax.swing.JPanel();
        cardThongTinKH = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lableHo = new javax.swing.JLabel();
        lableTaiKhoan = new javax.swing.JLabel();
        lableTen = new javax.swing.JLabel();
        lableNgayTao = new javax.swing.JLabel();
        lablePass = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txtTen = new javax.swing.JTextField();
        txtTaiKhoan = new javax.swing.JTextField();
        txtMatKhau = new javax.swing.JTextField();
        txtHo = new javax.swing.JTextField();
        btnCapNhat = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        cardLichSuMuaHang = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblChiTietDonHang = new javax.swing.JTable();
        jPanel11 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtMaDonHang = new javax.swing.JTextField();
        txtTenDonHang = new javax.swing.JTextField();
        txtTongGiamGia = new javax.swing.JTextField();
        txtNgayDat = new javax.swing.JTextField();
        txtTongTien = new javax.swing.JTextField();
        btnXoaDonHang = new javax.swing.JButton();
        btnChiTiet = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblDanhSachDonHang = new javax.swing.JTable();
        cardMuaHang = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblMatHangDaChon = new javax.swing.JTable();
        btnXoa = new javax.swing.JButton();
        btnXoaTatCa = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtTongHoaDon = new javax.swing.JTextField();
        btnXacNhan = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDanhSachMatHang = new javax.swing.JTable();
        btnChonSanPham = new javax.swing.JButton();
        txtSoLuongMua = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listDanhMuc = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jplSlideMenu.setBackground(new java.awt.Color(255, 255, 255));
        jplSlideMenu.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jplSlideMenu.setPreferredSize(new java.awt.Dimension(190, 590));
        jplSlideMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/Image/avatar.png"))); // NOI18N

        lable_TenKhachHang.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lable_TenKhachHang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lable_TenKhachHang.setText("Tên KH");
        lable_TenKhachHang.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblCloseMenu.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblCloseMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCloseMenu.setText("X");
        lblCloseMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCloseMenuMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(63, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(lblCloseMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(lable_TenKhachHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCloseMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lable_TenKhachHang)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jplSlideMenu.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 150));

        lblMuaHang.setBackground(new java.awt.Color(255, 255, 255));
        lblMuaHang.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblMuaHang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMuaHang.setText("Mua Hàng");
        lblMuaHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMuaHangMouseClicked(evt);
            }
        });
        jplSlideMenu.add(lblMuaHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 210, 30));

        lblThongTinKH.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblThongTinKH.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblThongTinKH.setText("Thông tin cá nhân");
        lblThongTinKH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblThongTinKHMouseClicked(evt);
            }
        });
        jplSlideMenu.add(lblThongTinKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 210, 30));

        lblLichSuMuaHang.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblLichSuMuaHang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLichSuMuaHang.setText("Lịch sử mua hàng");
        lblLichSuMuaHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLichSuMuaHangMouseClicked(evt);
            }
        });
        jplSlideMenu.add(lblLichSuMuaHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 210, 30));
        jplSlideMenu.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 452, 210, 10));

        labelDangXuat.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        labelDangXuat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelDangXuat.setText("Đăng Xuất");
        labelDangXuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelDangXuatMouseClicked(evt);
            }
        });
        jplSlideMenu.add(labelDangXuat, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 560, 210, 30));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Giới Thiệu");
        jplSlideMenu.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, 210, 30));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Trợ Giúp");
        jplSlideMenu.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, 210, 30));

        jPanel1.add(jplSlideMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 0, 600));

        jpllMenuBar.setBackground(new java.awt.Color(255, 255, 255));

        lblOpenMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/Image/menu.png"))); // NOI18N
        lblOpenMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblOpenMenuMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jpllMenuBarLayout = new javax.swing.GroupLayout(jpllMenuBar);
        jpllMenuBar.setLayout(jpllMenuBarLayout);
        jpllMenuBarLayout.setHorizontalGroup(
            jpllMenuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpllMenuBarLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblOpenMenu)
                .addContainerGap(1420, Short.MAX_VALUE))
        );
        jpllMenuBarLayout.setVerticalGroup(
            jpllMenuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpllMenuBarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblOpenMenu)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jpllMenuBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 1470, 40));

        jplTitle.setBackground(new java.awt.Color(0, 168, 255));

        javax.swing.GroupLayout jplTitleLayout = new javax.swing.GroupLayout(jplTitle);
        jplTitle.setLayout(jplTitleLayout);
        jplTitleLayout.setHorizontalGroup(
            jplTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1480, Short.MAX_VALUE)
        );
        jplTitleLayout.setVerticalGroup(
            jplTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel1.add(jplTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1480, 30));

        jplMain.setBackground(new java.awt.Color(255, 255, 255));
        jplMain.setLayout(new java.awt.CardLayout());

        cardThongTinKH.setBackground(new java.awt.Color(255, 255, 255));

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Họ :");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Ngày tạo :");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText("Tên :");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setText("Tài khoản :");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setText("Mật khẩu :");

        lableHo.setText("jLabel15");

        lableTaiKhoan.setText("jLabel15");

        lableTen.setText("jLabel15");

        lableNgayTao.setText("jLabel15");

        lablePass.setText("jLabel15");

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Chỉnh sửa thông tin", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel20.setText("Họ :");

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel21.setText("Tên :");

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel22.setText("Tài khoản :");

        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel23.setText("Mật khẩu :");

        txtTen.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtTaiKhoan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtMatKhau.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtHo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btnCapNhat.setText("Cập nhật");
        btnCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatActionPerformed(evt);
            }
        });

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel8Layout.createSequentialGroup()
                            .addComponent(btnCapNhat)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnReset))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel8Layout.createSequentialGroup()
                            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel21)
                                .addComponent(jLabel20)
                                .addComponent(jLabel23))
                            .addGap(34, 34, 34)
                            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtTen, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtHo, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(txtHo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(txtTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(txtTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(txtMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCapNhat)
                    .addComponent(btnReset))
                .addContainerGap(107, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel4)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel7))
                        .addGap(77, 77, 77)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lableNgayTao, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lablePass, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lableTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lableHo, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lableTen, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lableHo))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(lableTen))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(lableTaiKhoan))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(lablePass))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lableNgayTao))
                .addGap(48, 48, 48)
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout cardThongTinKHLayout = new javax.swing.GroupLayout(cardThongTinKH);
        cardThongTinKH.setLayout(cardThongTinKHLayout);
        cardThongTinKHLayout.setHorizontalGroup(
            cardThongTinKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardThongTinKHLayout.createSequentialGroup()
                .addGap(524, 524, 524)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(627, Short.MAX_VALUE))
        );
        cardThongTinKHLayout.setVerticalGroup(
            cardThongTinKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardThongTinKHLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(92, Short.MAX_VALUE))
        );

        jplMain.add(cardThongTinKH, "card3");

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CHI TIẾT ĐƠN HÀNG", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        tblChiTietDonHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tên sản phẩm", "Số lượng mua", "Giá giảm", "Thành tiền"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(tblChiTietDonHang);
        if (tblChiTietDonHang.getColumnModel().getColumnCount() > 0) {
            tblChiTietDonHang.getColumnModel().getColumn(0).setResizable(false);
            tblChiTietDonHang.getColumnModel().getColumn(1).setResizable(false);
            tblChiTietDonHang.getColumnModel().getColumn(2).setResizable(false);
            tblChiTietDonHang.getColumnModel().getColumn(3).setResizable(false);
        }

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 625, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jScrollPane5)
                .addContainerGap())
        );

        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DANH SÁCH ĐƠN HÀNG", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin đơn hàng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Tổng tiền");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Mã đơn hàng");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("Tên đơn hàng");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("Tổng giảm giá");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setText("Ngày đặt");

        txtMaDonHang.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtMaDonHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaDonHangActionPerformed(evt);
            }
        });

        txtTenDonHang.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtTenDonHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenDonHangActionPerformed(evt);
            }
        });

        txtTongGiamGia.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtTongGiamGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTongGiamGiaActionPerformed(evt);
            }
        });

        txtNgayDat.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNgayDat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNgayDatActionPerformed(evt);
            }
        });

        txtTongTien.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtTongTien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTongTienActionPerformed(evt);
            }
        });

        btnXoaDonHang.setText("Xóa đơn hàng");
        btnXoaDonHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaDonHangActionPerformed(evt);
            }
        });

        btnChiTiet.setText("Xem chi tiết");
        btnChiTiet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChiTietActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMaDonHang, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTenDonHang, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(290, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNgayDat, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTongGiamGia, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnXoaDonHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnChiTiet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(22, 22, 22))))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtMaDonHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtTenDonHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtTongGiamGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnChiTiet))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txtNgayDat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoaDonHang))
                .addContainerGap())
        );

        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh sách đơn hàng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N

        tblDanhSachDonHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã đơn hàng", "Tên đơn hàng", "Tổng tiền đơn hàng", "Giá giảm", "Ngày đặt"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDanhSachDonHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDanhSachDonHangMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblDanhSachDonHang);
        if (tblDanhSachDonHang.getColumnModel().getColumnCount() > 0) {
            tblDanhSachDonHang.getColumnModel().getColumn(0).setResizable(false);
            tblDanhSachDonHang.getColumnModel().getColumn(1).setResizable(false);
            tblDanhSachDonHang.getColumnModel().getColumn(2).setResizable(false);
            tblDanhSachDonHang.getColumnModel().getColumn(3).setResizable(false);
            tblDanhSachDonHang.getColumnModel().getColumn(4).setResizable(false);
        }

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 612, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout cardLichSuMuaHangLayout = new javax.swing.GroupLayout(cardLichSuMuaHang);
        cardLichSuMuaHang.setLayout(cardLichSuMuaHangLayout);
        cardLichSuMuaHangLayout.setHorizontalGroup(
            cardLichSuMuaHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cardLichSuMuaHangLayout.createSequentialGroup()
                .addContainerGap(116, Short.MAX_VALUE)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(248, 248, 248))
        );
        cardLichSuMuaHangLayout.setVerticalGroup(
            cardLichSuMuaHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardLichSuMuaHangLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cardLichSuMuaHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(182, Short.MAX_VALUE))
        );

        jplMain.add(cardLichSuMuaHang, "card4");

        cardMuaHang.setBackground(new java.awt.Color(255, 255, 255));
        cardMuaHang.setEnabled(false);
        cardMuaHang.setPreferredSize(new java.awt.Dimension(1500, 838));
        cardMuaHang.setRequestFocusEnabled(false);
        cardMuaHang.setVerifyInputWhenFocusTarget(false);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "MẶT HÀNG ĐÃ CHỌN", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N

        tblMatHangDaChon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã sản phẩm", "Tên sản phẩm", "Giá sản phẩm", "Giảm giá", "Số lượng mua", "Thành tiền"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Integer.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblMatHangDaChon);
        if (tblMatHangDaChon.getColumnModel().getColumnCount() > 0) {
            tblMatHangDaChon.getColumnModel().getColumn(0).setResizable(false);
            tblMatHangDaChon.getColumnModel().getColumn(1).setResizable(false);
            tblMatHangDaChon.getColumnModel().getColumn(2).setResizable(false);
            tblMatHangDaChon.getColumnModel().getColumn(3).setResizable(false);
            tblMatHangDaChon.getColumnModel().getColumn(4).setResizable(false);
            tblMatHangDaChon.getColumnModel().getColumn(5).setResizable(false);
        }

        btnXoa.setText("Xóa sản phẩm");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnXoaTatCa.setText("Xóa đơn đặt");
        btnXoaTatCa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaTatCaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 395, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(btnXoa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnXoaTatCa)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnXoa)
                    .addComponent(btnXoaTatCa))
                .addGap(30, 30, 30))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "THANH TOÁN", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N

        jLabel5.setText("Tổng hóa đơn:");

        btnXacNhan.setText("Xác nhận mua hàng");
        btnXacNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXacNhanActionPerformed(evt);
            }
        });

        jLabel6.setText("VNĐ");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(575, 575, 575)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(txtTongHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addGap(82, 82, 82)
                .addComponent(btnXacNhan)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtTongHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(btnXacNhan))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DANH SÁCH MẶT HÀNG", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N

        tblDanhSachMatHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã sản phẩm", "Tên sản phẩm", "Giá", "Giảm giá", "Mô tả"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblDanhSachMatHang);
        if (tblDanhSachMatHang.getColumnModel().getColumnCount() > 0) {
            tblDanhSachMatHang.getColumnModel().getColumn(0).setResizable(false);
            tblDanhSachMatHang.getColumnModel().getColumn(1).setResizable(false);
            tblDanhSachMatHang.getColumnModel().getColumn(2).setResizable(false);
            tblDanhSachMatHang.getColumnModel().getColumn(3).setResizable(false);
            tblDanhSachMatHang.getColumnModel().getColumn(4).setResizable(false);
        }

        btnChonSanPham.setText("Chọn");
        btnChonSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChonSanPhamActionPerformed(evt);
            }
        });

        jLabel2.setText("Số lượng mua");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txtSoLuongMua, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnChonSanPham))
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnChonSanPham)
                    .addComponent(txtSoLuongMua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DANH MỤC SẢN PHẨM", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N

        listDanhMuc.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listDanhMuc.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listDanhMucValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listDanhMuc);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout cardMuaHangLayout = new javax.swing.GroupLayout(cardMuaHang);
        cardMuaHang.setLayout(cardMuaHangLayout);
        cardMuaHangLayout.setHorizontalGroup(
            cardMuaHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardMuaHangLayout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addGroup(cardMuaHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(cardMuaHangLayout.createSequentialGroup()
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(315, Short.MAX_VALUE))
        );
        cardMuaHangLayout.setVerticalGroup(
            cardMuaHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardMuaHangLayout.createSequentialGroup()
                .addGroup(cardMuaHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(79, Short.MAX_VALUE))
        );

        jplMain.add(cardMuaHang, "card2");

        jPanel1.add(jplMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 1710, 760));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1476, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 835, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblCloseMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMenuMouseClicked
        closeMenu();
    }//GEN-LAST:event_lblCloseMenuMouseClicked

    private void lblOpenMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOpenMenuMouseClicked
        openMenu();
    }//GEN-LAST:event_lblOpenMenuMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        jplSlideMenu.setSize(0, y);
        x = 0;
    }//GEN-LAST:event_formWindowOpened

    private void lblMuaHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMuaHangMouseClicked
        cardMuaHang.setVisible(true);
        cardThongTinKH.setVisible(false);
        cardLichSuMuaHang.setVisible(false);
    }//GEN-LAST:event_lblMuaHangMouseClicked

    private void lblThongTinKHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblThongTinKHMouseClicked
        cardMuaHang.setVisible(false);
        cardThongTinKH.setVisible(true);
        cardLichSuMuaHang.setVisible(false);
    }//GEN-LAST:event_lblThongTinKHMouseClicked
    
    private void btnChonSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChonSanPhamActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblDanhSachMatHang.getSelectedRow();
        if (selectedRow != -1) { // Đảm bảo rằng một hàng đã được chọn
            DefaultTableModel modelDanhSachMatHang = (DefaultTableModel) tblDanhSachMatHang.getModel();
            DefaultTableModel modelMatHangDaChon = (DefaultTableModel) tblMatHangDaChon.getModel();
            Long maSP = Long.parseLong(modelDanhSachMatHang.getValueAt(selectedRow, 0).toString());
            String tenSP = modelDanhSachMatHang.getValueAt(selectedRow, 1).toString();
            double gia = Double.parseDouble(modelDanhSachMatHang.getValueAt(selectedRow, 2).toString());
            
            int soLuongMua;

            try {
                soLuongMua = Integer.parseInt(txtSoLuongMua.getText());
                if (soLuongMua <= 0) {
                    throw new NumberFormatException();
                }
                double giamGia = (Double.parseDouble(modelDanhSachMatHang.getValueAt(selectedRow, 3).toString()))*soLuongMua;
                double thanhTien = (gia * soLuongMua)-giamGia;

                // Thêm dữ liệu vào đầu bảng MatHangDaChon
                Vector<Object> rowData = new Vector<>();
                rowData.add(maSP);
                rowData.add(tenSP);
                rowData.add(gia);
                rowData.add(giamGia);
                rowData.add(soLuongMua);
                rowData.add(thanhTien);
                modelMatHangDaChon.insertRow(0, rowData); // Thêm dòng mới vào đầu bảng
                // Cập nhật tổng hóa đơn
                updateTotalBill();
            } catch (NumberFormatException e) {
                // Hiển thị thông báo nếu số lượng không hợp lệ
                JOptionPane.showMessageDialog(this, "Số lượng mua không hợp lệ. Vui lòng nhập số lượng lớn hơn 0.", "Lỗi", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            // Hiển thị thông báo nếu không có sản phẩm nào được chọn
            JOptionPane.showMessageDialog(this, "Chưa có sản phẩm nào được chọn. Vui lòng chọn một sản phẩm.", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
        txtSoLuongMua.setText("");
    }//GEN-LAST:event_btnChonSanPhamActionPerformed

    private void listDanhMucValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listDanhMucValueChanged
        // Lấy danh mục được chọn từ listDanhMuc
        String danhMucDuocChon = listDanhMuc.getSelectedValue();
        // Truy xuất danh sách sản phẩm tương ứng với danh mục được chọn từ cơ sở dữ liệu
        ArrayList<SanPham> dsSanPhamTheoDanhMuc = SanPhamDAO.layDanhSachSanPhamTheoDanhMuc(danhMucDuocChon);

        // Cập nhật dữ liệu cho bảng tblDanhSachMatHang
        DefaultTableModel dtmSanPham = (DefaultTableModel) tblDanhSachMatHang.getModel();
        dtmSanPham.setRowCount(0); // Xóa dữ liệu cũ trước khi cập nhật mới
        for (SanPham sp : dsSanPhamTheoDanhMuc) {
            Vector<Object> vec = new Vector<Object>();
            vec.add(sp.getTenSanPham());
            vec.add(sp.getGia());
            vec.add(sp.getHinhAnh());
            vec.add(sp.getMoTa());
            dtmSanPham.addRow(vec);
        }
        tblDanhSachMatHang.setModel(dtmSanPham);
        
    }//GEN-LAST:event_listDanhMucValueChanged

    private void btnXacNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXacNhanActionPerformed
        try {
            // Thu thập thông tin đơn hàng
            String tendonhang = "Đơn hàng của " + lable_TenKhachHang.getText();
            BigDecimal tongtien = new BigDecimal(txtTongHoaDon.getText());
            BigDecimal tonggiamgia = BigDecimal.ZERO;
            LocalDateTime ngaytao = LocalDateTime.now();
            Long MaND = maND;

            // Tạo đối tượng DonHang
            DonHang donHang = new DonHang(tendonhang, tongtien, tonggiamgia, ngaytao);
            donHang.setMaNguoiDung(maND);

            // Lưu đơn hàng vào cơ sở dữ liệu và lấy mã đơn hàng mới tạo
            boolean isDonHangSaved = DonHangDAO.themDonHang(donHang);
            if (!isDonHangSaved) {
                JOptionPane.showMessageDialog(this, "Lỗi khi lưu đơn hàng");
                return;
            }

            // Giả sử mã đơn hàng được trả về sau khi lưu
            Long maDonHang = donHang.getMadonhang();

            // Thu thập chi tiết sản phẩm từ bảng tblMatHangDaChon
            List<MucDonHang> dsMucDonHang = new ArrayList<>();
            DefaultTableModel modelMatHangDaChon = (DefaultTableModel) tblMatHangDaChon.getModel();
            for (int i = 0; i < modelMatHangDaChon.getRowCount(); i++) {
                Long maSanPham = Long.parseLong(modelMatHangDaChon.getValueAt(i, 0).toString());
                String tenSP = modelMatHangDaChon.getValueAt(i, 1).toString();
                BigDecimal giaHienTai = new BigDecimal(modelMatHangDaChon.getValueAt(i, 2).toString());
                BigDecimal giamGiaHienTai = new BigDecimal(modelMatHangDaChon.getValueAt(i, 3).toString());
                int soLuong = Integer.parseInt(modelMatHangDaChon.getValueAt(i, 4).toString());
                // Tính tổng giảm giá
                tonggiamgia = tonggiamgia.add(giamGiaHienTai);

                // Tạo đối tượng MucDonHang
                MucDonHang mucDonHang = new MucDonHang(soLuong, giaHienTai, giamGiaHienTai, maDonHang, maSanPham);
                dsMucDonHang.add(mucDonHang);
            }

            // Cập nhật tổng giảm giá vào đơn hàng
            donHang.setTonggiamgia(tonggiamgia);

            // Lưu chi tiết sản phẩm vào cơ sở dữ liệu
            boolean allMucDonHangSaved = true;
            for (MucDonHang mucDonHang : dsMucDonHang) {
                boolean isMucDonHangSaved = MucDonHangDAO.themMucDonHang(mucDonHang);
                if (!isMucDonHangSaved) {
                    allMucDonHangSaved = false;
                    break;
                }
            }

            if (allMucDonHangSaved) {
                JOptionPane.showMessageDialog(this, "Đơn hàng đã được lưu thành công!");
            } else {
                JOptionPane.showMessageDialog(this, "Lỗi khi lưu chi tiết sản phẩm");
            }

        } catch (Exception ex) {
            Logger.getLogger(this.getClass().getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Đã xảy ra lỗi: " + ex.getMessage());
        }
        loadData();
       
    }//GEN-LAST:event_btnXacNhanActionPerformed

    private void btnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatActionPerformed
        long MaND = maND;
        String hoKH = txtHo.getText();
        String tenKH = txtTen.getText();
        String taiKhoan = txtTaiKhoan.getText();
        String matKhau = txtMatKhau.getText();
        // Kiểm tra xem đã nhập đủ thông tin hay chưa
        if (hoKH.isEmpty() || tenKH.isEmpty() || taiKhoan.isEmpty() || matKhau.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin người dùng.");
            return;
        }
        NguoiDung nd = new NguoiDung(MaND,hoKH,tenKH,taiKhoan,matKhau,"Khách hàng");
        boolean kq = NguoiDungDAO.capNhatNguoiDung(nd);          
        // Cập nhật thông tin người dùng trong cơ sở dữ liệu
        if (kq) {
            JOptionPane.showMessageDialog(this, "Cập nhật thông tin người dùng thành công.");
            lable_TenKhachHang.setText(txtHo.getText() + " " +  txtTen.getText());
        } else {
            JOptionPane.showMessageDialog(this, "Cập nhật thông tin người dùng không thành công. Vui lòng thử lại sau.");
        }
        
        loadData();
    }//GEN-LAST:event_btnCapNhatActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // Lấy mô hình bảng từ JTable
        DefaultTableModel model = (DefaultTableModel) tblMatHangDaChon.getModel();
        // Lấy chỉ số của dòng được chọn
        int selectedRow = tblMatHangDaChon.getSelectedRow();
        // Kiểm tra xem có dòng nào được chọn không
        if (selectedRow != -1) {
            // Lấy tên sản phẩm từ dòng được chọn, giả sử tên sản phẩm ở cột thứ 2 (index 1)
            String tenSanPham = model.getValueAt(selectedRow, 0).toString();
            // Hiển thị hộp thoại xác nhận
            int response = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn xóa sản phẩm \"" + tenSanPham + "\" khỏi đơn hàng?", "Xác nhận", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            // Nếu người dùng chọn "Yes"
            if (response == JOptionPane.YES_OPTION) {
                // Xóa dòng được chọn
                model.removeRow(selectedRow);
                updateTotalBill();
            }
        } else {
            // Hiển thị thông báo nếu không có dòng nào được chọn
            JOptionPane.showMessageDialog(this, "Vui lòng chọn một dòng để xóa.");
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnXoaTatCaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaTatCaActionPerformed
         int response = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn xóa tất cả các mặt hàng trong đơn hàng?", "Xác nhận", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        // Nếu người dùng chọn "Yes"
        if (response == JOptionPane.YES_OPTION) {
            // Lấy mô hình bảng từ JTable
            DefaultTableModel model = (DefaultTableModel) tblMatHangDaChon.getModel();
            // Xóa tất cả các hàng trong mô hình bảng
            model.setRowCount(0);
            updateTotalBill();
        }
    }//GEN-LAST:event_btnXoaTatCaActionPerformed
    
    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        ThongTinKhachHang();
    }//GEN-LAST:event_btnResetActionPerformed

    private void lblLichSuMuaHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLichSuMuaHangMouseClicked
        cardMuaHang.setVisible(false);
        cardThongTinKH.setVisible(false);
        cardLichSuMuaHang.setVisible(true);
    }//GEN-LAST:event_lblLichSuMuaHangMouseClicked

    private void txtMaDonHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaDonHangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaDonHangActionPerformed

    private void txtTenDonHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenDonHangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenDonHangActionPerformed

    private void txtTongGiamGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTongGiamGiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTongGiamGiaActionPerformed

    private void txtNgayDatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNgayDatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNgayDatActionPerformed

    private void txtTongTienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTongTienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTongTienActionPerformed

    private void btnChiTietActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChiTietActionPerformed
        // Lấy mã đơn hàng từ JTextField
        Long maDonHang = Long.parseLong(txtMaDonHang.getText());
        // Truy vấn dữ liệu từ bảng MucDonHang dựa trên mã đơn hàng
        ArrayList<MucDonHang> dsMucDonHang = MucDonHangDAO.layDanhSachMucDonHangTheoMaDonHang(maDonHang);
        DefaultTableModel model = new DefaultTableModel();
        // Thêm các cột vào model
        model.addColumn("Tên sản phẩm");
        model.addColumn("Số lượng mua");
        model.addColumn("Giá giảm");
        model.addColumn("Thành tiền");
        // Thêm dữ liệu từ danh sách mục đơn hàng vào model
        for (MucDonHang mucDonHang : dsMucDonHang) {
            // Tính toán thành tiền
            BigDecimal soLuong = new BigDecimal(mucDonHang.getSoLuong());
            BigDecimal giaHienTai = mucDonHang.getGiaHienTai();

            // Tính toán thành tiền
            BigDecimal thanhTien = soLuong.multiply(giaHienTai);

            // Thêm hàng mới vào model
            model.addRow(new Object[]{
                mucDonHang.getTenSanPham(), // Sử dụng phương thức lấy tên sản phẩm
                mucDonHang.getSoLuong(),
                mucDonHang.getGiamGiaHienTai(),
                thanhTien
            });
        }

        // Cập nhật model cho bảng tblChiTietDonHang
        tblChiTietDonHang.setModel(model);
    }//GEN-LAST:event_btnChiTietActionPerformed

    private void tblDanhSachDonHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDanhSachDonHangMouseClicked
        // TODO add your handling code here:
        int row = tblDanhSachDonHang.getSelectedRow();
        if (row != -1) {
            txtMaDonHang.setText(String.valueOf(tblDanhSachDonHang.getValueAt(row, 0)));
            txtTenDonHang.setText(String.valueOf(tblDanhSachDonHang.getValueAt(row, 1)));
            txtTongTien.setText(String.valueOf(tblDanhSachDonHang.getValueAt(row, 2)));
            txtTongGiamGia.setText(String.valueOf(tblDanhSachDonHang.getValueAt(row, 3)));
            txtNgayDat.setText(String.valueOf(tblDanhSachDonHang.getValueAt(row, 4)));
        }
    }//GEN-LAST:event_tblDanhSachDonHangMouseClicked

    private void btnXoaDonHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaDonHangActionPerformed
        Long maDonHang = Long.parseLong(txtMaDonHang.getText());
        int confirmed = JOptionPane.showConfirmDialog(null, "Bạn có chắc chắn muốn xóa đơn hàng này?", "Xác nhận xóa đơn hàng", JOptionPane.YES_NO_OPTION);
        if (confirmed == JOptionPane.YES_OPTION) {
            // Thực hiện xóa đơn hàng từ cơ sở dữ liệu
            boolean deleted = DonHangDAO.xoaDonHang(maDonHang);
            if (deleted) {
                JOptionPane.showMessageDialog(null, "Đơn hàng đã được xóa thành công.");
                // Cập nhật giao diện hoặc làm các công việc khác sau khi xóa
            } else {
                JOptionPane.showMessageDialog(null, "Đã xảy ra lỗi khi xóa đơn hàng.");
            }
        }
        hienThiDanhSachDonHangCuaNguoiDung();
    }//GEN-LAST:event_btnXoaDonHangActionPerformed

    private void labelDangXuatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelDangXuatMouseClicked
        int choice = JOptionPane.showConfirmDialog(rootPane, "Bạn có muốn đăng xuất không?", "Xác nhận thoát", JOptionPane.YES_NO_CANCEL_OPTION);
        switch (choice) {
            case JOptionPane.YES_OPTION:
                gui.view.Login formLogin = new  gui.view.Login();
                formLogin.setVisible(true);
                this.dispose();
            // Nếu người dùng chọn No, không làm gì cả
            case JOptionPane.NO_OPTION:
                break;
            // Nếu người dùng chọn Cancel, không làm gì cả
            case JOptionPane.CANCEL_OPTION:
                break;
            default:
                break;
        }
    }//GEN-LAST:event_labelDangXuatMouseClicked
    private void updateTotalBill() {
        DefaultTableModel modelMatHangDaChon = (DefaultTableModel) tblMatHangDaChon.getModel();
        double tongHoaDon = 0.0;
        for (int i = 0; i < modelMatHangDaChon.getRowCount(); i++) {
            tongHoaDon += Double.parseDouble(modelMatHangDaChon.getValueAt(i, 5).toString());
        }
        // Loại bỏ phần thập phân .0 nếu tổng hóa đơn là số nguyên
        if (tongHoaDon == (int) tongHoaDon) {
            txtTongHoaDon.setText(String.valueOf((int) tongHoaDon));
        } else {
            txtTongHoaDon.setText(String.valueOf(tongHoaDon));
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                // Tạo một instance mới của Menu và truyền các thông tin cần thiết
                new Menu(maND, ho, ten).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnChiTiet;
    private javax.swing.JButton btnChonSanPham;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnXacNhan;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton btnXoaDonHang;
    private javax.swing.JButton btnXoaTatCa;
    private javax.swing.JPanel cardLichSuMuaHang;
    private javax.swing.JPanel cardMuaHang;
    private javax.swing.JPanel cardThongTinKH;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel jplMain;
    private javax.swing.JPanel jplSlideMenu;
    private javax.swing.JPanel jplTitle;
    private javax.swing.JPanel jpllMenuBar;
    private javax.swing.JLabel labelDangXuat;
    private javax.swing.JLabel lableHo;
    private javax.swing.JLabel lableNgayTao;
    private javax.swing.JLabel lablePass;
    private javax.swing.JLabel lableTaiKhoan;
    private javax.swing.JLabel lableTen;
    private javax.swing.JLabel lable_TenKhachHang;
    private javax.swing.JLabel lblCloseMenu;
    private javax.swing.JLabel lblLichSuMuaHang;
    private javax.swing.JLabel lblMuaHang;
    private javax.swing.JLabel lblOpenMenu;
    private javax.swing.JLabel lblThongTinKH;
    private javax.swing.JList<String> listDanhMuc;
    private javax.swing.JTable tblChiTietDonHang;
    private javax.swing.JTable tblDanhSachDonHang;
    private javax.swing.JTable tblDanhSachMatHang;
    private javax.swing.JTable tblMatHangDaChon;
    private javax.swing.JTextField txtHo;
    private javax.swing.JTextField txtMaDonHang;
    private javax.swing.JTextField txtMatKhau;
    private javax.swing.JTextField txtNgayDat;
    private javax.swing.JTextField txtSoLuongMua;
    private javax.swing.JTextField txtTaiKhoan;
    private javax.swing.JTextField txtTen;
    private javax.swing.JTextField txtTenDonHang;
    private javax.swing.JTextField txtTongGiamGia;
    private javax.swing.JTextField txtTongHoaDon;
    private javax.swing.JTextField txtTongTien;
    // End of variables declaration//GEN-END:variables
    void ThongTinKhachHang()
    {
        NguoiDung nguoiDung = NguoiDungDAO.layThongTinNguoiDung(maND);
        // Kiểm tra xem người dùng có tồn tại không
        if (nguoiDung != null) {
            // Gán thông tin người dùng vào các label
            lableHo.setText(nguoiDung.getHo());
            txtHo.setText(nguoiDung.getHo());
            lableTen.setText(nguoiDung.getTen());
            txtTen.setText(nguoiDung.getTen());
            lableTaiKhoan.setText(nguoiDung.getTenTaiKhoan());
            txtTaiKhoan.setText(nguoiDung.getTenTaiKhoan());
            lablePass.setText(nguoiDung.getMatKhau());
            txtMatKhau.setText(nguoiDung.getMatKhau());
            // Định nghĩa một DateTimeFormatter cho định dạng ngày/tháng/năm
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
            // Sử dụng DateTimeFormatter để định dạng lại ngày tạo thành chuỗi ngày/tháng/năm
            String ngayTaoFormatted = nguoiDung.getNgayTao().format(formatter);
            lableNgayTao.setText(ngayTaoFormatted);
        } else {
            JOptionPane.showMessageDialog(this, "Không tìm thấy thông tin người dùng");
        }
    }

    public void hienThiDanhSachDonHangCuaNguoiDung() {

        // Truy vấn cơ sở dữ liệu để lấy danh sách các đơn hàng của người dùng đang đăng nhập từ bảng tblDanhSachDonHang
        ArrayList<DonHang> dsDonHang = DonHangDAO.layDanhSachDonHangCuaNguoiDung(maND);

        // Tạo một DefaultTableModel để chứa dữ liệu cho bảng
        DefaultTableModel model = new DefaultTableModel();
        
        // Thêm các cột vào model
        model.addColumn("Mã đơn hàng");
        model.addColumn("Tên đơn hàng");
        model.addColumn("Tổng tiền");
        model.addColumn("Giảm giá");
        model.addColumn("Ngày đặt");
        
        // Tạo DateTimeFormatter với định dạng mong muốn
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");

        // Thêm dữ liệu từ danh sách đơn hàng vào model, đồng thời định dạng ngày đặt
        for (DonHang dh : dsDonHang) {
            Object[] row = dh.toRow();
            // Định dạng ngày đặt từ LocalDateTime thành chuỗi theo định dạng "dd/MM/yyyy"
            row[4] = dh.getNgaytao().format(formatter);
            model.addRow(row);
        }
        // Cập nhật model cho bảng
        tblDanhSachDonHang.setModel(model);
    }

}
